### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [stinachen/PieHard#44]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by stinachen** [comment]
Currently, we have signed off this IP to the University of Michigan - Ann Arbor. This is a Major Design Project for Computer Science.
